aws:
  bucket.name: edm-ecommerce
  client.region: s3://${aws.bucket.name}
  key:
    access: USERNAME
    secret: PASSWORD
# SPRING DATA --------------------------------------------------------------------------------------
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/lms_platform?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    username: trungnt
#    password: trungnt2010
#    driver-class-name: com.mysql.cj.jdbc.Driver
# EUREKA CLIENT CONFIG
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
ribbon:
  listOfServers: http://localhost:8890
# LOGGING --------------------------------------------------------------------------------------
logging:
  level:
    vn.edu.topica: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.netflix:
      discover: false
      eureka: false

# JWT --------------------------------------------------------------------------------------
authen.jwtSecret: Basic
authen.jwt.expiredTime: 43200
aws.access.key.id: test
# LIQUIBASE - DEFAULT DISABLE
spring.liquibase:
  enabled: false

# SSO
sso:
  url:
    get-user-info: http://staging-sso.edumall.vn/sso/user_info