#add for off eureka set to false
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: local

server:
  port: 8082
---
spring:
  profiles: docker

server:
  port: 8080