eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

---
spring:
  profiles: local

server:
  port: 8082
---
spring:
  profiles: docker

server:
  port: 8080