server:
   port: 8866
spring:
   profiles:
      active: native
   cloud:
      config:
         server:
            native:
               searchLocations: file:/Users/trungnt/edumall/lms-platform/cloud/config-app/files-config-repo